jspp/urls.py
from django.conf.urls import url
from . import views
app_name = 'jspp'

urlpatterns = [

    # /jspp/
    url(r'^$', views.IndexView.as_view(), name='index'),

    
]

superlist/urls.py
from django.conf.urls import url
from . import views
app_name = 'superlist'

urlpatterns = [
    # /superlist/
    # /show nothing but homepage
    url(r'^$', views.home_page, name='home'),
    # /superlist/list/new
    # add new list
    url(r'^new$', views.new_list, name='new_list'),
    # /superlist/list/77
    # show special list
    url(r'^(\d+)/$', views.view_list, name='view_list'),
]

superlist/models.py
from django.db import models
from django.core.urlresolvers import reverse

class List(models.Model):
    def get_absolute_url(self):
        return reverse('superlist:view_list', args=[self.id])

class Item(models.Model):
    text = models.CharField(default='', blank=False, max_length=200)
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

    class Meta:
        # not work in mysql
        unique_together = ('list', 'text')
        ordering = ('id',)

    def __str__(self):
        return self.text

superlist/forms.py
from django.core.exceptions import ValidationError
from django import forms
from .models import Item

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)

        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': "Enter a to-do item",
                'class': 'form-control input-lg',
            }),
        }

        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }

    def save(self, for_list):
        self.instance.list = for_list
        return super().save()


class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        # call super().super().save(), instead of super.save()
        return forms.models.ModelForm.save(self)

superlist/views.py
# from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
# from django.http import HttpResponse
# csrf_exempt close the csrf check
from django.views.decorators.csrf import csrf_exempt
from .models import Item, List
from .forms import ItemForm, ExistingListItemForm


def home_page(request):
    return render(request, 'superlist/home.html', {'form': ItemForm()})

@csrf_exempt
def view_list(request, list_id):

    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)

    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)

    return render(request, 'superlist/list.html', {'list': list_, 'form': form})


@csrf_exempt
def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        # if get error
        return render(request, 'superlist/home.html', {'form': form})

templates/superlist/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Language" content="zh-TW">

        <title>{% block title %}To-Do lists{% endblock title %}</title>
        <link rel="stylesheet" type="text/css" href="{% static "bootstrap-3.3.7/css/bootstrap.min.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "superlist/base.css" %}">
    </head>
    <body>
        <div class="container">       
            <div class="row">
                <div class="col-md-6 col-md-offset-3 jumbotron">
                    <div class="text-center">
                        <h1>{% block header_text %}{% endblock header_text %}</h1>
                        <form method="POST" action='{% block form_action %}{% endblock form_action %}'>
                            {{ form.text }}
                            {% if form.errors %}
                                <div class="form-group, has-error">
                                    <span class="help-block">{{ form.text.errors }}</span>
                                </div>
                            {% endif %}
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    {% block table %}  
                        {% url 'flavors:flavor_rest_api' %}             
                    {% endblock table %}  
                </div>   
            </div>
        </div>  
        <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
        <script type="text/javascript" src="{% static "tests/superlist.js" %}"></script>

    </body>

</html>

templates/superlist/home.html
{% extends "superlist/base.html" %}
{% block title %}{{ block.super }} | Homepage{% endblock title %}
{% block header_text %}Start a new To-Do lists{% endblock header_text %}
{% block form_action %}{% url 'superlist:new_list' %}{% endblock form_action %}
{% block table %}{% endblock table %}

templates/superlist/list.html
{% extends "superlist/base.html" %}

{% block title %}{{ block.super }} | List{% endblock title %}

{% block header_text %}Your To-Do lists{% endblock header_text %}

{% block form_action %}{% url 'superlist:view_list' list.id %}{% endblock form_action %}

{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
            <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
            
        {% endfor %} 
       
       
    </table>
            
{% endblock table %}