jspp/urls.py
from django.conf.urls import url
from . import views
app_name = 'jspp'

urlpatterns = [

    # /jspp/
    url(r'^$', views.IndexView.as_view(), name='index'),

    
]

music/urls.py
from django.conf.urls import url
from . import views
app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /music/login/
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    # /music/logout/
    url(r'^login/$', views.LogoutView.as_view(), name='logout'),
    # /music/register/
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # /music/71/
    # 71 is album_id
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    
    # /music/album/add/
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    # /music/album/71/
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    # /music/album/71/delete
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
    # /music/<album_id>/favorite/
    # url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),

]

music/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class Album(models.Model):
    user = models.ForeignKey(User, default=1)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    # FK to Album，
    album = models.ForeignKey(Album, on_delete=models.CASCADE,)
    song_title = models.CharField(max_length=250, default=None)
    audio_file = models.FileField(default='')
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

    def set_favorite(self):
        if (self.is_favorite is True):
            self.is_favorite = False
        else:
            self.is_favorite = True
        self.save()
        return None

music/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth import authenticate, login


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class LoginForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Enter Account'}), label='Account')
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Enter Password'}))

    class Meta:
        model = User
        fields = ['username', 'password']      

music/views.py
# from django.http import Http404
# from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views import generic
from django.views.generic import View, FormView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Album, Song
from .forms import UserForm, LoginForm
from django.contrib.auth.mixins import LoginRequiredMixin


class LoginView(View):
    form_class = LoginForm
    template_name = 'music/login.html'

    # display blank LoginForm
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process user data
    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        # 驗證帳號
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                # 登入後重導
                login(request, user)
                return redirect('music:index')
        else:
            form = self.form_class(request.POST)
            # not login
            return render(request, self.template_name, {'form': form, 'error_message': 'Account or password error'})


class LogoutView(View):
    templates_name = 'music/login.html'
    form_class = LoginForm

    def get(self, request):
        form = self.form_class(None)
        logout(request)

        return render(request, self.template_name, {'form': form, 'error_message': 'Logout success!'})


class IndexView(LoginRequiredMixin, generic.ListView):

    login_url = "/music/login/"
    template_name = "music/index.html"
    # default is object_list
    context_object_name = "albums"

    def get_queryset(self):
        return Album.objects.all()


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(LoginRequiredMixin, CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumUpdate(LoginRequiredMixin, UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

    model = Album


class AlbumDelete(LoginRequiredMixin, DeleteView):
    success_url = reverse_lazy('music:index')
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        # check data
        if form.is_valid():

            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            # password need 加密
            user.set_password(password)
            user.save()

            # return User objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')
        else:
            # not login
            return render(request, self.template_name, {'form': form})


# def favorite(request, album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     try:
#         selected_song = album.song_set.get(pk=request.POST['song'])
#     except(KeyError, Song.DoesNotExist):
#         return render(request, 'music/detail.html', {
#             'album': album,
#             'error_message': "You did not select a valid song",
#         })
#     else:
#         # set True to False,False to True
#         selected_song.set_favorite()
#     return render(request, 'music/detail.html', {'album': album})

templates/music/album_form.html
{% extends "base.html" %}
{% block title %}Add a New Album{% endblock title %}
{% block album_activate %}active{% endblock album_activate %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include "music/form-templates.html" %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type=submit class="btn btn-success">Submit</button>
                            </div>
                        </div>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>


</div>
{% endblock body %}

templates/music/detail.html
{% extends "base.html" %}

{% block title %}{{ block.super }}:Album detail{% endblock title %}
{% block body %}

   <div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="">View All</a></li>
                <li role="presentation"><a href="">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>

                                <td>
                                    <form action="" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>
<script type="text/javascript">

\
</script>

{% endblock body %}

templates/music/form-templates.html
{% for field in form  %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>       
    </div>    
{% endfor %}
{{error_message}}

templates/music/index.html
{% extends 'base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Albums</h3>
        </div>
        {% if albums %}
            {% for album in albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{album.album_logo.url}}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="#" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:album-add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Album</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.song_title }}</td>
                                        <td>{{ song.album.artist }}</td>
                                        <td>
                                            <a target="_blank" href="{{ song.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:detail' song.album.id %}">
                                                <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

templates/music/login.html
{% extends "base_visitor.html" %}
{% block title %}{{ block.super }} - Login{% endblock title %}
{% block login_active %}active{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Member Login</h3>
                    <form class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include "music/form-templates.html" %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type=submit class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'music:register' %}">Click here</a> to register.
                </div>
            
            </div>
        </div>
    </div>
</div>
{% endblock body %}

templates/music/registration_form.html
{% extends "base_visitor.html" %}
{% block title %}Register{% endblock title %}
{% block register_active %}active{% endblock register_active %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a New Account</h3>
                    <form class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include "music/form-templates.html" %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type=submit class="btn btn-success">Submit</button>
                            </div>
                        </div>
                        
                    </form>
                </div>

                

            </div>
        </div>
    </div>


</div>
{% endblock body %}