jspp/urls.py
from django.conf.urls import url
from . import views
app_name = 'jspp'

urlpatterns = [

    # /jspp/
    url(r'^$', views.IndexView.as_view(), name='index'),

    
]

music/urls.py
from django.conf.urls import url
from . import views
app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /music/login/
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    # /music/logout/
    url(r'^login/$', views.LogoutView.as_view(), name='logout'),
    # /music/register/
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # /music/71/
    # 71 is album_id
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    
    # /music/album/add/
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    # /music/album/71/
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    # /music/album/71/delete
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
    # /music/<album_id>/favorite/
    # url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}Viberr{% endblock title %}
    </title>
    <!-- load the path to your static files -->
    {% load staticfiles %}
    <!-- bootstrap  -->
    <link rel="stylesheet" type="text/css" href="{% static "bootstrap-3.3.7/css/bootstrap.min.css" %}">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static "music/style.css" %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="{% static "bootstrap-3.3.7/js/bootstrap.min.js" %}"></script>
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
            </div>
            <!-- End Header-->
            <!-- Items-->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="{% block albums_active %}{% endblock %}">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"> </span>&nbsp; Albums
                        </a>
                    </li>
                    <li class="{% block songs_active %}{% endblock %}">
                        <a href="#">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"> </span>&nbsp;Songs
                        </a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'music:album-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"> </span>&nbsp;Add Album
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'music:logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"> </span>&nbsp;Logout
                        </a>
                    </li>
                </ul>
            </div>
            <!-- End  Items-->
        </div>
    </nav>
    {% block body %} {% endblock body %}
    <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
    <script type="text/javascript" src="{% static "tests/superlist.js" %}"></script>

</body>

</html>

templates/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'music:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'music:login' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/javascript_test.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>javascript practice</title>
    <script src="{% static "jspp/main.js" %}" type="text/javascript"></script>
</head>
<body>
<p id="sayhello"></p> 

<button id = "demo_date_now" onclick="document.getElementById('demo_date_now').innerHTML = Date()">get time now</button>  

<script type="text/javascript">
    
     
    
</script>

</body>
</html>